language: elixir

elixir:
  - 1.5.0

otp_release:
  - 20.0

services:
  - postgresql

before_script:
  - MIX_ENV=test mix event_store.create
  - MIX_ENV=test mix do ecto.create, ecto.migrate

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
